name: build and publish to gitHub packages

on:
  push:
    tags:
      - "v*" # Ex: v1.0.0

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Instalar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          registry-url: "https://npm.pkg.github.com"

      - name: Instalar dependências
        run: npm ci

      - name: Build da lib
        run: npm run build

      - name: publish to gitHub packages
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
